# -*- coding:utf-8 -*-

from django.conf.urls import patterns, include, url

from yepes.apps import apps

ImageView = apps.get_class('newsletters.views', 'ImageView')
LinkView = apps.get_class('newsletters.views', 'LinkView')
MessageView = apps.get_class('newsletters.views', 'MessageView')
#NewsletterDetailView = apps.get_class('newsletters.views', 'NewsletterDetailView')
#NewsletterListView = apps.get_class('newsletters.views', 'NewsletterListView')
ProfileView = apps.get_class('newsletters.views', 'ProfileView')
ResubscriptionView = apps.get_class('newsletters.views', 'ResubscriptionView')
SubscriptionView = apps.get_class('newsletters.views', 'SubscriptionView')
UnsubscriptionView = apps.get_class('newsletters.views', 'UnsubscriptionView')
UnsubscriptionReasonView = apps.get_class('newsletters.views', 'UnsubscriptionReasonView')


urlpatterns = patterns('',
    #url(r'^$',
        #NewsletterListView.as_view(),
        #name='newsletter_list',
    #),
    url(r'^images/(?P<image_guid>[0-9a-f]+)/$',
        ImageView.as_view(),
        name='image',
    ),
    url(r'^images/(?P<subscriber_guid>[0-9a-f]+)/(?P<message_guid>[0-9a-f]+)/(?P<image_guid>[0-9a-f]+)/$',
        ImageView.as_view(),
        name='image',
    ),
    url(r'^links/(?P<link_guid>[0-9a-f]+)/$',
        LinkView.as_view(),
        name='link',
    ),
    url(r'^links/(?P<subscriber_guid>[0-9a-f]+)/(?P<message_guid>[0-9a-f]+)/(?P<link_guid>[0-9a-f]+)/$',
        LinkView.as_view(),
        name='link',
    ),
    url(r'^messages/(?P<message_guid>[0-9a-f]+)/$',
        MessageView.as_view(),
        name='message',
    ),
    url(r'^messages/(?P<message_guid>[0-9a-f]+)/(?P<subscriber_guid>[0-9a-f]+)/$',
        MessageView.as_view(),
        name='message',
    ),
    url(r'^messages/(?P<message_guid>[0-9a-f]+)/\?s=(?P<subscriber_guid>[0-9a-f]+)$',
        MessageView.as_view(),
        name='message',
    ),
    url(r'^profile/(?P<subscriber_guid>[0-9a-f]+)/$',
        ProfileView.as_view(),
        name='profile',
    ),
    url(r'^profile/(?P<subscriber_guid>[0-9a-f]+)/\?m=(?P<message_guid>[0-9a-f]+)$',
        ProfileView.as_view(),
        name='profile',
    ),
    url(r'^profile/(?P<subscriber_guid>[0-9a-f]+)/\?n=(?P<newsletter_guid>[0-9a-f]+)$',
        ProfileView.as_view(),
        name='profile',
    ),
    url(r'^profile/(?P<subscriber_guid>[0-9a-f]+)/\?n=(?P<newsletter_guid>[0-9a-f]+)&m=(?P<message_guid>[0-9a-f]+)$',
        ProfileView.as_view(),
        name='profile',
    ),
    url(r'^resubscribe/(?P<newsletter_guid>[0-9a-f]+)/(?P<subscriber_guid>[0-9a-f]+)/$',
        ResubscriptionView.as_view(),
        name='resubscription',
    ),
    url(r'^subscribe/$',
        SubscriptionView.as_view(),
        name='subscription',
    ),
    url(r'^subscribe/(?P<newsletter_guid>[0-9a-f]+)/$',
        SubscriptionView.as_view(),
        name='subscription',
    ),
    url(r'^subscribe/(?P<newsletter_guid>[0-9a-f]+)/(?P<subscriber_guid>[0-9a-f]+)/$',
        SubscriptionView.as_view(),
        name='subscription',
    ),
    url(r'^unsubscribe/$',
        UnsubscriptionView.as_view(),
        name='unsubscription',
    ),
    url(r'^unsubscribe/(?P<newsletter_guid>[0-9a-f]+)/$',
        UnsubscriptionView.as_view(),
        name='unsubscription',
    ),
    url(r'^unsubscribe/(?P<newsletter_guid>[0-9a-f]+)/\?m=(?P<message_guid>[0-9a-f]+)$',
        UnsubscriptionView.as_view(),
        name='unsubscription',
    ),
    url(r'^unsubscribe/(?P<newsletter_guid>[0-9a-f]+)/(?P<subscriber_guid>[0-9a-f]+)/$',
        UnsubscriptionView.as_view(),
        name='unsubscription',
    ),
    url(r'^unsubscribe/(?P<newsletter_guid>[0-9a-f]+)/(?P<subscriber_guid>[0-9a-f]+)/\?m=(?P<message_guid>[0-9a-f]+)$',
        UnsubscriptionView.as_view(),
        name='unsubscription',
    ),
    url(r'^unsubscribe-reason/(?P<newsletter_guid>[0-9a-f]+)/(?P<subscriber_guid>[0-9a-f]+)/$',
        UnsubscriptionReasonView.as_view(),
        name='unsubscription_reason',
    ),
    #url(r'^(?P<newsletter_slug>[-\w]+)/$',
        #NewsletterDetailView.as_view(),
        #name='newsletter_detail',
    #),
)
