language: python

python:
  - '2.7'
  - '3.4'
  - '3.5'

env:
  - DJANGO_VERSION=1.8 GRAPPELLI_VERSION=2.7
  - DJANGO_VERSION=1.9 GRAPPELLI_VERSION=2.8
  - DJANGO_VERSION=1.10 GRAPPELLI_VERSION=2.9
  - DJANGO_VERSION=1.11 GRAPPELLI_VERSION=2.10

before_install:
  - pip install -q coveralls
  - pip install -q -r requirements/test.txt
  - pip install -q -U "Django<$DJANGO_VERSION"
  - pip install -q -U "django-grappelli<$GRAPPELLI_VERSION"

install:
  - python setup.py install

script:
  - python tests/runtests.py --with-coverage --cover-branches --cover-package=yepes

after_success:
  - coveralls
